# Generated by Django 5.2 on 2025-04-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_answers_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_src',
            field=models.CharField(default='N/A', max_length=510),
        ),
    ]
